artifacts:
  - path: '**\*.nupkg'

configuration:
  - Release

before_build:
  - cmd: dotnet restore Pocket.Logger.sln /p:Version=%APPVEYOR_BUILD_VERSION%

build_script:
  - cmd: >-
      dotnet build Pocket.Logger.sln /p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - cmd: >-
      dotnet pack .\Pocket.Logger\Pocket.Logger.csproj --no-build /p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: dotnet test .\Pocket.Logger\Pocket.Logger.csproj

hosts:
  api.nuget.org: 93.184.221.200