artifacts:
  - path: '**\*.nupkg'

configuration:
  - Release

before_build:
  - cmd: dotnet restore Pocket.Logger.sln 

build_script:
  - cmd: >-
      dotnet build Pocket.Logger.sln 

after_build:
  - nuget pack Pocket.Logger\PocketLogger.nuspec  
  - nuget pack Pocket.Logger\PocketLogger.Subscribe.nuspec  
  - nuget pack Pocket.Logger\PocketLogger.For.ApplicationInsights.nuspec  
  - nuget pack Pocket.Logger\Disposable.nuspec  

test_script:
  - cmd: dotnet test .\Pocket.Logger\Pocket.Logger.csproj